global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'patient-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['patient-service:4000']

  - job_name: 'auth-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['auth-service:4005']

  - job_name: 'billing-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['billing-service:4002']

  - job_name: 'analytics-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['analytics-service:4003']

  - job_name: 'api-gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['api-gateway:4004']