spring.application.name=billing-service

server.port=4002
grpc.server.port=9002
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always
management.metrics.tags.application=billing-service