spring.application.name=PatientManagementMicroservice
server.port=4000
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.ByteArraySerializer
logging.level.root=info
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always