version: '3.8'

services:
  billing-service:
    build:
      context: ../
      dockerfile: billing-service/Dockerfile
    image: billing-service
    container_name: billing-service
    ports:
      - "4002:4002"
      - "9002:9002"
    networks:
      - microservice-net

networks:
  microservice-net:
    external: true

